# Generated by Django 4.2.6 on 2023-11-02 18:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodsInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dietary_restriction', models.CharField(max_length=50)),
                ('food_name', models.CharField(max_length=50)),
                ('food_description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('open_hours', models.IntegerField()),
                ('available_for_pickup', models.DateTimeField()),
                ('cuisine_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
    ]
