# Generated by Django 4.2.7 on 2023-12-03 21:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryManager', '0002_foodsinventory_restaurant_alter_question_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodsinventory',
            name='expiration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='foodsinventory',
            name='food_category',
            field=models.CharField(default='to-go', max_length=50),
        ),
        migrations.AddField(
            model_name='foodsinventory',
            name='food_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='foodsinventory',
            name='package_size',
            field=models.CharField(default='0', max_length=500),
        ),
        migrations.AlterField(
            model_name='foodsinventory',
            name='dietary_restriction',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='foodsinventory',
            name='food_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='cuisine_type',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='location',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='open_hours',
            field=models.CharField(max_length=500),
        ),
    ]
